spring.application.name=guiarestaurante

app.datasource.url: jdbc:mysql://localhost:3306/guiarestaurante?createDatabaseIfNotExist=true
app.datasource.username: root
app.datasource.password: P@$$w0rd
app.datasource.driver-class-name: com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto: update
spring.jpa.show-sql: true
spring.jpa.properties.hibernate.format_sql: true